# How to edit the config:

# port: 
    #AUTO - automaticly detects port (Experimental feature)
    #manual - Check your COM port in Device Manager (It should look like this -> port: COMx)
port: AUTO

# baudrate: Same Baud Rate as the one in arduinoCode.ino
baudrate: 57600

# invertSliders: Explains itself
invertSliders: false

# apps: List your apps here
#       Check the application name in Task Manager -> Details
#       App names are not case sensitive
#       Special controls: master - controls master volume
#                         mic - controls your microphone volume
#                         activeWindow - controls currently focused window volume 
#       group: Group multiple apps together
apps:
    - master
    - firefox
    - activeWindow
    - Discord
    - group:
            - PathOfExileSteam
            - cs2
            - GeometryDash
            - RustClient